# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5256568b19dfc46c580d65a5c8c50445db66de2e887f993b26bd6adc8a369527f534bf176cdd1d2a670a014db9a476bd09766b2fe562e2d32ab571e8b30fbcca

test:
  secret_key_base: b161293f680bef919de33de155290370adba0d88699f3376d37f362ade66ad791b6cd87706e270d7c3336a7bc5a575329a26345fb4af095eced81a883179877c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
